server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: myAPI
          uri: http://localhost:8100
          predicates:
            - Path=/api/**
          filters:
          - RewritePath=/api/(?<path>.*), /$\{path}
  main:
    web-application-type: reactive 
